### PR TITLE
Bump bitcoin dependency to ^0.29, minor related fixes

### PR DESCRIPTION
**Pull request by notmandatory**
This version bump for `bitcoin` dependency is required to fix https://github.com/bitcoindevkit/bdk/issues/646.

### CODE REVIEW

**Comment by afilini** [comment]
I would wait for #83 and #84 to be merged first. I'm planning to make one more release that's still on 0.28 because we can't update bdk yet, but i would still like to have the new features and fixes for the next bdk release.

Once that release is done we can merge this and make another release, which we will hopefully use in bdk next month once miniscript is also updated for 0.29

**Comment by notmandatory** [comment]
I'll rebase this one after #83 and #84 are merged.

**Comment by afilini** [comment]
You can go ahead and rebase now :)

**Review by afilini — APPROVED** [review]
ACK d132572c14edfad0c7f9e8e4a1acd8267ff914a1

**Pull request merged**
